In [ ]:
import torch

In [ ]:
print('torch version: ', torch.__version__)

torch version:  1.7.0+cu101


In [ ]:
# tensor는 행렬이라고 생각!

t = torch.tensor([[1,2], [3,4]])
print(t)

tensor([[1, 2],
        [3, 4]])


In [ ]:
print(t.size())

torch.Size([2, 2])


In [ ]:
t2 = torch.tensor([[1,2], [3,4]], device='cuda')
print(t2)

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [ ]:
print(t2.dtype)

torch.int64


In [ ]:
t3 = torch.arange(0,10)
print(t3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
print(t3.size())

torch.Size([10])


In [ ]:
print(t3.dtype)

torch.int64


## Tensor를 자동으로 만드는 방법

### 0으로만 구성된 tensor를 만드는 방법

In [ ]:
z1 = torch.zeros(2,3)
print(z1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(z1.size(), z1.dtype)

torch.Size([2, 3]) torch.float32


### 정규분포 (평균 0, 분산 1)를 따르는 임의의 숫자들로 구성된 tensor를 생성

In [ ]:
z2 = torch.rand(2,3)
print(z2)

tensor([[0.9378, 0.8011, 0.3036],
        [0.1430, 0.9072, 0.9440]])


In [ ]:
print(z2.size(), z2.dtype)

torch.Size([2, 3]) torch.float32


### 1로만 구성된 tensor를 만든다.

In [ ]:
z3 = torch.ones(2,3)
print(z3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor에서 일부분만 읽거나, 쓰는 방법

In [ ]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
print(t1.size())  # 2행 3열

torch.Size([2, 3])


In [ ]:
# t1에서 3 추출
k = t1[0,2]
print(type(k), k.size(), k.dtype)
print(k)

<class 'torch.Tensor'> torch.Size([]) torch.int64
tensor(3)


In [ ]:
print(k.data.item())

3


### 2행 2열만 추출,,,

In [ ]:
t2 = t1[:, :2]
print(t2)

tensor([[1, 2],
        [4, 5]])


In [ ]:
t3 = t1[0, 1:]
print(t3)

tensor([2, 3])


In [ ]:
t4 = t1[1:, 1:]
print(t4, t4.size())

tensor([[5, 6]]) torch.Size([1, 2])


In [ ]:
t5 = t1[:, [0,2]]
print(t5)

tensor([[1, 3],
        [4, 6]])


In [ ]:
t6 = t1[t1 > 3]
print(t6)

tensor([4, 5, 6])


In [ ]:
t7 = t1[t1 > 2]
print(t7)

tensor([3, 4, 5, 6])


In [ ]:
t8 = torch.tensor([[1,2,3], [4,5,6]])
print(t8)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
t8[0,1] = 100
print(t8)

tensor([[  1, 100,   3],
        [  4,   5,   6]])


In [ ]:
t8[:,1] = 200
print(t8)

tensor([[  1, 200,   3],
        [  4, 200,   6]])


In [ ]:
t8[t8 > 100] = -1
print(t8)

tensor([[ 1, -1,  3],
        [ 4, -1,  6]])


### Tensor 연산

In [ ]:
v = torch.tensor([1,2,3.])
w = torch.tensor([0, 10, 20.])
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])

In [ ]:
# 행렬과 스칼라의 곱
m2 = m + 2.0
print(m2)

tensor([[  2.,   3.,   4.],
        [102., 202., 302.]])


In [ ]:
# (2,3)인 행렬과 (3,)인 벡터의 덧셈이므로 각 행에 적용된다.
m3 = m + v
print(m3)

tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])


In [ ]:
# 행렬간의 덧셈
m4 = m + m
print(m4)

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


### randn, torch.abs

In [ ]:
X = torch.randn(5, 10)  # 5행 10열
y = X * 2 + torch.abs(X)
print(y)

tensor([[-7.2639e-01, -8.2851e-01,  9.8163e-01,  7.1511e+00,  1.6373e+00,
          1.4882e+00, -1.5379e+00, -1.8484e+00,  1.9991e-03, -6.5756e-01],
        [ 1.5076e+00, -8.7449e-01, -3.2859e-01,  5.0625e+00, -2.9687e+00,
         -7.5577e-01, -1.0595e+00, -7.4228e-01,  7.3657e-01, -1.7986e+00],
        [-7.8519e-02, -7.0970e-01,  3.8332e+00, -7.1689e-01,  3.4674e+00,
         -1.0747e+00, -2.0328e+00, -9.9852e-01, -2.1485e+00,  2.2049e+00],
        [-8.3291e-01,  3.1210e-01, -6.1080e-02, -3.3475e-01, -4.9762e-01,
          1.0910e+00,  2.2067e+00, -1.5369e-01, -1.0568e+00, -5.8618e-01],
        [-2.5748e-01,  4.5865e+00, -1.5993e+00, -6.7962e-01, -4.1302e-01,
         -2.0390e+00, -2.1650e-01,  4.3847e+00,  3.5724e+00, -2.5103e-01]])


### torch.mean

In [ ]:
# 평균 구하기
X = torch.tensor([[1,1,1], [2,2,2]], dtype=torch.float)
print(X.dtype)

m = torch.mean(X)
print(m)

m = X.mean()
print(m)

torch.float32
tensor(1.5000)
tensor(1.5000)


In [ ]:
# 0차원인 Tensor는 item 메소드로 값을 추출할 수 있다.
k = m.item()
print(k)

1.5


### torch.mean 행과 열을 지정

In [ ]:
x = torch.tensor([[1,1,1], [2,2,2]], dtype=torch.float)

print(torch.mean(x,0))  # 0은 행, 1은 열 -> 즉 , x의 행끼리 계산해서 평균 값을 계산해라.

tensor([1.5000, 1.5000, 1.5000])


In [ ]:
print(torch.mean(x,1))

tensor([1., 2.])


### 행렬 Tensor의 인덱스 조작

In [ ]:
x1 = torch.tensor([[1,2], [3, 4.]]) # 2x2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]])  # 2x3

In [ ]:
x1.view(4,1)  #  2x2를 4x1로 차원을 변경한다.

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [ ]:
x1.view(1,-1) # -1을 사용하면 표현할 수 있는 자동화된 값으로 대체(행, 열 둘 중에서 한 곳만 사용 가능)
# 갯수만 맞으면 아무 숫자나 올 수 있음

tensor([[1., 2., 3., 4.]])

In [ ]:
x2.t()  # 2x3을 전치해서 3x2로 만든다. t => transpose

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])

In [ ]:
torch.cat([x1, x2], dim=1)  # dim=1로 결합하면 열에 붙여서 2x5의 Tensor로 만든다.(concatenate)

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])